name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 0.9.0)'
        required: true
        default: '0.9.0'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore RPOverlayApp.sln
      
    - name: Update version in project file
      shell: pwsh
      run: |
        $version = "${{ github.event.inputs.version }}"
        $csprojPath = "RPOverlay.WPF\RPOverlay.WPF.csproj"
        $content = Get-Content $csprojPath -Raw
        $content = $content -replace '<Version>[\d\.]+</Version>', "<Version>$version</Version>"
        $content = $content -replace '<AssemblyVersion>[\d\.]+</AssemblyVersion>', "<AssemblyVersion>$version.0</AssemblyVersion>"
        $content = $content -replace '<FileVersion>[\d\.]+</FileVersion>', "<FileVersion>$version.0</FileVersion>"
        Set-Content $csprojPath $content
        Write-Host "Updated version to $version"
        
    - name: Build self-contained single-file application
      run: |
        dotnet publish RPOverlay.WPF\RPOverlay.WPF.csproj `
          --configuration Release `
          --runtime win-x64 `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          -p:EnableCompressionInSingleFile=true `
          --output ./publish
          
    - name: Create ZIP archive
      shell: pwsh
      run: |
        $version = "${{ github.event.inputs.version }}"
        $zipName = "RPOverlay-v$version-win-x64.zip"
        $files = Get-ChildItem -Path ./publish -File | Where-Object { $_.Extension -ne ".pdb" }
        Compress-Archive -Path $files.FullName -DestinationPath $zipName
        Write-Host "Created archive: $zipName"
        
    - name: Create Release with GitHub CLI
      shell: pwsh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $version = "${{ github.event.inputs.version }}"
        $zipName = "RPOverlay-v$version-win-x64.zip"
        $tag = "v$version"
        
        # Create release notes
        $releaseNotes = @"
        ## RPOverlay v$version
        
        ### Installation
        1. Ladda ner .exe-filen nedan
        2. Kör `RPOverlay.WPF.exe`
        
        ### Systemkrav
        - Windows 10/11 (x64)
        - .NET 8.0 Runtime (ingår i self-contained versionen)
        
        ### Ändringar
        Se [commits](https://github.com/${{ github.repository }}/commits/$tag) för detaljer.
        "@
        
        # Create release and upload asset
        gh release create $tag $zipName `
          --title "RPOverlay v$version" `
          --notes $releaseNotes
